### ISSUE TITLE
[Feature Request] Rootless support

### ISSUE THREAD

**Issue by F-Unction** [NyaMisty/Surge4Advanced#6]
求做一下rootless越狱的适配，比如Dopamine？🥺

**Comment by F-Unction** [comment]
我尝试了不更改代码直接rootless打包，github actions config在我的fork里面（https://github.com/F-Unction/Surge4Advanced/blob/master/.github/workflows/build-deb.yml）
出现的问题是一些framework的路径还是没有改变，但是我在插件代码中没有找到任何硬编码的路径
![963A323F-E073-41E0-9B5B-CD17A7916FD4](https://user-images.githubusercontent.com/51352133/236657792-d61f92c6-824d-4920-bc05-925b1034d27d.png)

**Comment by F-Unction** [comment]
又尝试了用theos还没合入的pr（https://github.com/theos/theos/pull/737） 来构建，但出现了闪退，不过我不懂怎么调试和查找崩溃原因

**Comment by NyaMisty** [comment]
不错，能自己编译出来已经挺厉害的了。问题主要是特征码变了。
